name: Deploy Supply Chain

on:
  push:
    branches:
      - develop
      - staging
      - main
  workflow_dispatch:

jobs:

  deploy-development:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest

    environment:
      name: development
      url: https://supply-chain-development.onrender.com

    steps:
      - name: Deploy Development Frontend
        run: curl -X POST "${{ secrets.FRONTEND_DEPLOY_HOOK }}"

      - name: Deploy Development Backend
        run: curl -X POST "${{ secrets.BACKEND_DEPLOY_HOOK }}"


  deploy-staging:
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest

    environment:
      name: staging
      url: https://supply-chain-staging.onrender.com

    steps:
      - name: Deploy Staging Frontend
        run: curl -X POST "${{ secrets.FRONTEND_DEPLOY_HOOK }}"

      - name: Deploy Staging Backend
        run: curl -X POST "${{ secrets.BACKEND_DEPLOY_HOOK }}"


  deploy-production:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    environment:
      name: production
      url: https://supply-chain-production.onrender.com

    steps:
      - name: Deploy Production Frontend
        run: curl -X POST "${{ secrets.FRONTEND_DEPLOY_HOOK }}"

      - name: Deploy Production Backend
        run: curl -X POST "${{ secrets.BACKEND_DEPLOY_HOOK }}"
